# Generated by Django 6.0.7 on 2026-07-24 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desk', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('desk', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, choices=[('RISK_LIMIT_BREACH', 'Risk Limit Breach'), ('INSUFFICIENT_MARGIN', 'Insufficient Margin'), ('INVALID_SYMBOL', 'Invalid Symbol'), ('EXCHANGE_TIMEOUT', 'Exchange Timeout')], max_length=30, null=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='monitoring.trader')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_id', models.CharField(max_length=20, unique=True)),
                ('fill_quantity', models.PositiveIntegerField()),
                ('fill_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('filled_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='monitoring.order')),
            ],
            options={
                'ordering': ['-filled_at'],
                'indexes': [models.Index(fields=['order', 'filled_at'], name='monitoring__order_i_96ee91_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('HIGH_LATENCY', 'High Latency'), ('DUPLICATE_FILL', 'Duplicate Fill'), ('REJECT_SPIKE', 'Reject Spike'), ('STALE_ORDER', 'Stale Order')], max_length=20)),
                ('desk', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_flags', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='monitoring.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['acknowledged', '-created_at'], name='monitoring__acknowl_19af28_idx'), models.Index(fields=['flag_type'], name='monitoring__flag_ty_c4f0c7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['desk', 'status'], name='monitoring__desk_9bc6df_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='monitoring__status_3ff492_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['symbol'], name='monitoring__symbol_591a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='monitoring__created_5da725_idx'),
        ),
    ]
